### ISSUE TITLE
Support for specific version and/or --patch --minor flags

### ISSUE THREAD

**Issue by chrismo** [readysteady/bundle-diff#1]
Cool gem!! I love it.

`bundle outdated` includes flags to restrict its output to only the next patch or minor release of a gem. It'd obviously take a bit more work to discover the gem version to grab, rather than just the newest one, but it's a feature I think would be cool to add, fwiw.

**Comment by timcraft** [comment]
Thanks! Hope you find it useful.

Both of these features would be good to have, I use those flags with outdated. The main difference is outdated typically reports on multiple gems, but I think the semantics are close enough.

**Comment by timcraft** [comment]
Version option added in 4b2619c (available in v1.1.0)
